# Ruby linting configuration.
#
# If you can avoid disabling a check globally by disabling it for just a method
# or file, that is prefered. If you disable a check, document why.

AllCops:
  TargetRubyVersion: 2.1
  Include:
    - lib/**/*.rb
  Exclude:
    - bin/**/*
    - exe/**/*
    - benchmark/**/*
    - script/**/*
    - vendor/**/*
    - tmp/**/*
Layout/AlignHash:
  EnforcedHashRocketStyle: table
Layout/AlignParameters:
  Enabled: false # https://git.io/vFfR7
Layout/EmptyLinesAroundAccessModifier:
  Enabled: false # Because we specify `private` per method, this would get ugly
Layout/EndOfLine:
  EnforcedStyle: native
Layout/ExtraSpacing:
  AllowForAlignment: true
Layout/FirstParameterIndentation:
  EnforcedStyle: consistent
Layout/IndentationWidth:
  Severity: error
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/IndentHeredoc:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundOperators:
  Enabled: true
Lint/EndAlignment:
  Severity: error
Lint/UnreachableCode:
  Severity: error
Lint/UselessAccessModifier:
  Enabled: false # Because we specify `private` per method
Metrics/AbcSize:
  Max: 21
Metrics/BlockLength:
  Exclude:
    - test/**/*.rb
    - lib/jekyll/configuration.rb
    - rake/*.rake
    - jekyll.gemspec
Metrics/ClassLength:
  Exclude:
    - !ruby/regexp /features\/.*.rb$/
    - !ruby/regexp /test\/.*.rb$/
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/LineLength:
  Exclude:
    - !ruby/regexp /features\/.*.rb/
    - Rakefile
    - rake/*.rake
    - Gemfile
    - jekyll.gemspec
  Max: 90
  Severity: warning
Metrics/MethodLength:
  CountComments: false
  Max: 20
  Severity: error
Metrics/ModuleLength:
  Max: 240
Metrics/ParameterLists:
  Max: 4
Metrics/PerceivedComplexity:
  Max: 8
Naming/FileName:
  Exclude:
    - Gemfile
    - Rakefile
    - lib/theme_template/Gemfile
Security/MarshalLoad:
  Exclude:
    - !ruby/regexp /test\/.*.rb$/
    - lib/jekyll/regenerator.rb
Security/YAMLLoad:
  Exclude:
    - !ruby/regexp /features\/.*.rb/
    - !ruby/regexp /test\/.*.rb$/
Style/Alias:
  Enabled: false # We have no guidance on alias vs alias_method https://git.io/vFf0R
Style/AndOr:
  Severity: error
Style/ClassAndModuleChildren:
  Enabled: false # module X<\n>module Y is just as good as module X::Y. https://git.io/vFfEs
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
Style/Documentation:
  Enabled: false # This *SHOULD* be enabled
  Exclude:
    - !ruby/regexp /features\/.*.rb$/
Style/DoubleNegation:
  Enabled: false # This *SHOULD* be enabled
Style/GuardClause:
  Enabled: false # This *SHOULD* be enabled
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Severity: error
Style/ModuleFunction:
  Enabled: false
Style/MultilineTernaryOperator:
  Severity: error
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%q": "{}"
    "%Q": "{}"
    "%r": "!!"
    "%s": "()"
    "%w": "()"
    "%W": "()"
    "%x": "()"
Style/RedundantSelf:
  Enabled: false # Sometimes a self.field is a bit more clear https://git.io/vFf00
Style/RegexpLiteral:
  EnforcedStyle: percent_r
Style/SignalException:
  EnforcedStyle: only_raise
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
