---
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
   - vendor/**/*

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  AlignWith: variable

Lint/UnusedMethodArgument:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/BracesAroundHashParameters:
  Enabled: false
