bundler_args: --without benchmark:development
script: script/cibuild
cache: bundler
language: ruby

rvm:
  - &ruby1 2.6.0

matrix:
  include:
    - rvm: *ruby1
      env: TEST_SUITE=default-site
      name: "Default Site"
    - rvm: *ruby1
      env: TEST_SUITE=profile-docs
      name: "Profile Docs"
    - rvm: *ruby1
      env: TEST_SUITE=memprof
      name: "Profile Memory Allocation"

env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
    - master

notifications:
  email: false

before_install:
  - gem update --system
  - gem install bundler
