bundler_args: --without benchmark:development

script:
  - script/bootstrap
  - script/memprof
  - script/test
  - script/cucumber

cache: bundler
language: ruby

rvm:
  - 2.6.0
  - 2.4.5
env:
  matrix:
    - ROUGE_EDGE=true

branches:
  only:
    -master

before_install:
  - gem update --system
  - gem install bundler
