script: script/cibuild
bundler_args: --without doc:util:site:benchmark:development
before_script: bundle update
language: ruby
cache: bundler
sudo: false
rvm:
- 2.0
- 2.1
- 2.2
- jruby-9.0.3.0
- ruby-head

matrix:
  fast_finish: true
  allow_failures:
  - rvm: jruby-9.0.3.0
  - rvm: ruby-head
env:
  matrix:
    - TEST_SUITE=test
    - TEST_SUITE=cucumber
branches:
  only:
  - master
notifications:
  irc:
    channels: irc.freenode.org#jekyll
    template: "%{repository}#%{build_number} (%{branch}) %{message} %{build_url}"
  email:
    recipients:
    - jordon@envygeeks.io
  slack:
    secure: "\
      dNdKk6nahNURIUbO3ULhA09/vTEQjK0fNbgjVjeYPEvROHgQBP1cIP3AJy8aWs8rl5Yyow4Y\
      GEilNRzKPz18AsFptVXofpwyqcBxaCfmHP809NX5PHBaadydveLm+TNVao2XeLXSWu+HUNAY\
      O1AanCUbJSEyJTju347xCBGzESU=\
    "
