- name: Regeneration
  description: Enable auto-regeneration of the site when files are modified.
  flag: "-w, --[no-]watch"


- name: Configuration
  description: >-
    Specify config files instead of using <code>_config.yml</code> automatically.
    Settings in later files override settings in earlier files.
  flag: "--config FILE1[,FILE2,...]"


- name: Plugins
  description: >-
    Specify plugin directories instead of using <code>_plugins/</code> automatically.
  option: "plugins_dir: [ DIR1,... ]"
  flag: "-p, --plugins DIR1[,DIR2,...]"


- name: Layouts
  description: >-
    Specify layout directory instead of using <code>_layouts/</code> automatically.
  option: "layouts_dir: DIR"
  flag: --layouts DIR


- name: Drafts
  description: Process and render draft posts.
  option: "show_drafts: BOOL"
  flag: -D, --drafts


- name: Environment
  description: Use a specific environment value in the build.
  flag: JEKYLL_ENV=production


- name: Future
  description: Publish posts or collection documents with a future date.
  option: "future: BOOL"
  flag: --future


- name: Unpublished
  description: Render posts that were marked as unpublished.
  option: "unpublished: BOOL"
  flag: --unpublished


- name: LSI
  description: >-
    Produce an index for related posts. Requires the
    <a href="https://jekyll.github.io/classifier-reborn/">classifier-reborn</a> plugin.
  option: "lsi: BOOL"
  flag: --lsi


- name: Limit posts
  description: Limit the number of posts to parse and publish.
  option: "limit_posts: NUM"
  flag: --limit_posts NUM


- name: Force polling
  description: Force watch to use polling.
  option: "force_polling: BOOL"
  flag: --force_polling


- name: Verbose output
  description: Print verbose output.
  option: "verbose: BOOL"
  flag: -V, --verbose


- name: Silence output
  description: Silence the normal output from Jekyll during a build.
  option: "quiet: BOOL"
  flag: -q, --quiet


- name: Log level
  description: Specify a log level among debug, info, warn, or error.
  flag: JEKYLL_LOG_LEVEL=info


- name: Incremental build
  description: >-
    Enable the experimental
    <a href="/docs/configuration/incremental-regeneration/">incremental
    build</a> feature. Incremental build only re-builds posts and pages that
    have changed, resulting in significant performance improvements for large
    sites, but may also break site generation in certain cases.
  option: "incremental: BOOL"
  flag: -I, --incremental


- name: Disable bundle require
  description: Disables the need to require gems in `:jekyll_plugins` Gemfile
  flag: JEKYLL_NO_BUNDLER_REQUIRE=true


- name: Liquid profiler
  description: Generate a Liquid rendering profile to help you identify performance bottlenecks.
  option: "profile: BOOL"
  flag: --profile


- name: Strict front matter
  description: Cause a build to fail if there is a YAML syntax error in a page's front matter.
  option: "strict_front_matter: BOOL"
  flag: --strict_front_matter


- name: Web service URL
  option: "url: SCHEME://HOST[:PORT]"
  description: >-
    The actual Web service address in your production environment, should include the following components:
    <ol>
      <li>Protocol scheme(e.g. <code>http://</code>)</li>
      <li>Hostname or IP address(e.g. <code>example.org</code>)</li>
      <li>(Optional) Number of the web service's listening port(e.g. <code>8080</code>)</li>
    </ol>
    The value of this configuration option should NOT have a trailing slash.  It will be concatenated with the <code>baseurl</code> to form the full URL to your Jekyll site.
    <br>
    The value of this configuration option can be accessed using the <code>site.url</code> <a href="https://jekyllrb.com/docs/variables/#site-variables">Site Variables</a>.

- name: Base URL
  description: Serve the website from the given base URL.
  option: "baseurl: URL"
  flag: -b, --baseurl URL


- name: Trace
  description: Show the full backtrace when an error occurs.
  flag: -t, --trace
