markdown: kramdown
highlighter: pygments
relative_permalinks: false
permalink: /news/:year/:month/:day/:title/
excerpt_separator: noifniof3nioaniof3nioafafinoafnoif
exclude: [vendor]

# custom
gauges_id: 503c5af6613f5d0f19000027
repository: https://github.com/jekyll/jekyll
help_url: https://github.com/jekyll/jekyll-help
google_analytics_id: UA-50755011-1
timezone: America/Los_Angeles
