name: Continuous Integration

on:
  push:
    branches:
    - master
    - /.*-stable/
  pull_request:
    branches:
    - master
    - /.*-stable/

jobs:
  ci:
    if: "!contains(github.event.commits[0].message, '[ci skip]')"
    name: '${{ matrix.test_suite.name }} with Ruby ${{ matrix.ruby_version }}'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        ruby_version:
        - 2.5.x
        - 2.7.x
        test_suite:
        - name: Unit Tests
          id: test
        - name: Cucumber Features
          id: cucumber
        - name: Default Site
          id: default-site
        include:
          - ruby_version: 2.7.x
            test_suite:
            - name: Profile Docs site
              id: profile-docs
            - name: Memory Profile Docs site
              id: memprof

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5
    - name: "Set up Ruby ${{ matrix.ruby_version }}"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: 'Update Rubygems and Bundler'
      run: |
        gem update --system --no-document
        gem update bundler --no-document
    - name: Set up bundle
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run Test Suite
      run: bash script/cibuild
      env:
        CI: true
        TEST_SUITE: ${{ matrix.test_suite.id }}
