name: Ruby

on:
  push:
    branches:
    - master
    - /.*-stable/

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
    matrix:
      os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem update --system
        gem install bundler
        bundle install --jobs 4 --retry 3
        script/test
